[tox]
minversion = 4.0.0
envlist =
    lint
    docs
    py{39,310,311,312,313,314}
isolated_build = True

[testenv]
description = Run unit-testing
dependency_groups =
    test
# do not put * in passenv as it may break builds due to reduced isolation
passenv =
    CI
    GITHUB_*
    HOME
    PYTEST_*
    SSH_AUTH_SOCK
    TERM
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONUNBUFFERED=1
commands =
    pytest --cov-report term-missing --cov=rich tests/ {posargs}

[testenv:lint]
description = Runs all linting tasks
dependency_groups =
    lint
commands =
    black --check .
    mypy -p rich --no-incremental
skip_install = true

[testenv:docs]
description = Builds documentation
dependency_groups =
    docs
commands =
    sphinx-build -M html docs/source docs/build
