import subprocess

from wcwidth import list_versions
from wcwidth.table_wide import WIDE_EASTASIAN
from wcwidth.table_zero import ZERO_WIDTH

UNICODE_VERSIONS: list[str] = list_versions()

for version in UNICODE_VERSIONS:
    table: list[tuple[int, int, int]] = []
    wide_east_asian: list[tuple[int, int]] = WIDE_EASTASIAN.get(version, [])
    for start, end in wide_east_asian:
        table.append((start, end, 2))
    zero_wide: list[tuple[int, int]] = ZERO_WIDTH.get(version, [])
    for start, end in zero_wide:
        table.append((start, end, 0))

    table_file = f"""# Auto generated by tools/make_width_tables.py

CELL_WIDTHS = {table!r}

"""
    path = f"../rich/unicode{version}.py"
    with open(path, "wt") as file_out:
        file_out.write(table_file)

    subprocess.run("black {path}", shell=True)
