name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check .
      - run: codespell --ignore-words-list="ba,hel,womens" --skip="./README.de.md,./README.es.md,./README.sv.md,*.svg" || true
      - run: flake8 . --count --select=E9,F63,F7 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install colorama commonmark pygments
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
