on:
  release:
    types: [ released ]


jobs:
  asv-publish-and-copy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
      - run: 'pip install asv'
      - run: 'asv publish'
      - uses: cpina/github-action-push-to-another-repository@v1.4.1
        name: 'Copy files to Textualize/rich-benchmarks repo'
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUBLISH_ASV }}
        with:
          source-directory: /benchmarks/html
          destination-github-username: Textualize
          destination-repository-name: rich-benchmarks
          user-email: darren@textualize.io
